export enum DatabaseTypes {
    MYSQL8_4 = 'mysql8_4',
    MYSQL8 = 'mysql',
    POSTGRESQL17 = 'postgres17',
    POSTGRESQL16 = 'postgres16',
    POSTGRESQL15 = 'postgres15',
    POSTGRESQL14 = 'postgres14',
    REDIS8_1 = 'redis8_1',
    REDIS7 = 'redis7',
    MONGODB8_0 = 'mongodb8_0',
    MONGODB7 = 'mongodb7',
    OPENSEARCH2_19 = 'opensearch2_19',
    OPENSEARCH = 'opensearch',
    CLICKHOUSE25 = 'clickhouse25',
    CLICKHOUSE24 = 'clickhouse24',
    CLICKHOUSE = 'clickhouse',
    KAFKA = 'kafka',
    RABBITMQ4 = 'rabbitmq4_0',
    RABBITMQ = 'rabbitmq',
}
